name: Auto merge upstream
on:
  schedule:
  - cron: '* * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge upstream
      run: |
        git config --global user.name 'Tyler Ramer'
        git config --global user.email 'tylarb@users.noreply.github.com'

        git pull --unshallow
        git remote add upstream https://github.com/gravitational/teleport.git
        git fetch upstream

        git checkout -b feature/x origin/feature/x
        git merge --no-edit upstream/feature/x
        git push origin feature/x

        git checkout master
        git merge --no-edit upstream/master
        git push origin master

